SERVER.PORT : 80
# profile - default

#jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# spring boot - actuator expose
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
        
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: ENC(ztwh1STPLCTQ4UPOvTaYb+nW3XuWrtvOmTG1uU7jSMwBxiOMBygmcQ==)
    password: ENC(V9EGqX4WVUW3a+36KgGPWdnkQSBjPmqjvYpMO5su8S8adj1TI6MpBQ==)
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 20
      pool-name: SpringBootJPAHikariCP
      auto-commit: false  
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      

logging:
  file: spring
  file.path: /app/ktwiz/  
  level:
    root: INFO
    com.kt: INFO
    org.springframework: INFO

    
  